---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: usages.apiextensions.crossplane.io
spec:
  group: apiextensions.crossplane.io
  names:
    kind: Usage
    listKind: UsageList
    plural: usages
    singular: usage
  scope: Cluster
  versions:
  - name: v1alpha1
    served: true
    storage: true
    schema:
      openAPIV3Schema:
        type: object
        x-kubernetes-preserve-unknown-fields: true
    subresources:
      status: {}
    additionalPrinterColumns:
    - name: DETAILS
      type: string
      jsonPath: .metadata.annotations.crossplane\.io/usage-details
    - name: READY
      type: string
      jsonPath: .status.conditions[?(@.type=='Ready')].status
    - name: AGE
      type: date
      jsonPath: .metadata.creationTimestamp
