//go:build !ignore_autogenerated

// SPDX-FileCopyrightText: 2025 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by controller-gen. DO NOT EDIT.

package common

import ()

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ApplicationData) DeepCopyInto(out *ApplicationData) {
	*out = *in
	if in.BrokerURL != nil {
		in, out := &in.BrokerURL, &out.BrokerURL
		*out = new(string)
		**out = **in
	}
	if in.Credentials != nil {
		in, out := &in.Credentials, &out.Credentials
		*out = new(Credentials)
		(*in).DeepCopyInto(*out)
	}
	if in.Name != nil {
		in, out := &in.Name, &out.Name
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ApplicationData.
func (in *ApplicationData) DeepCopy() *ApplicationData {
	if in == nil {
		return nil
	}
	out := new(ApplicationData)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Credentials) DeepCopyInto(out *Credentials) {
	*out = *in
	if in.SecretName != nil {
		in, out := &in.SecretName, &out.SecretName
		*out = new(string)
		**out = **in
	}
	if in.HardcodedCreds != nil {
		in, out := &in.HardcodedCreds, &out.HardcodedCreds
		*out = new(HardcodedCreds)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Credentials.
func (in *Credentials) DeepCopy() *Credentials {
	if in == nil {
		return nil
	}
	out := new(Credentials)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HardcodedCreds) DeepCopyInto(out *HardcodedCreds) {
	*out = *in
	if in.User != nil {
		in, out := &in.User, &out.User
		*out = new(string)
		**out = **in
	}
	if in.Password != nil {
		in, out := &in.Password, &out.Password
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HardcodedCreds.
func (in *HardcodedCreds) DeepCopy() *HardcodedCreds {
	if in == nil {
		return nil
	}
	out := new(HardcodedCreds)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *InstanceData) DeepCopyInto(out *InstanceData) {
	*out = *in
	if in.InstanceId != nil {
		in, out := &in.InstanceId, &out.InstanceId
		*out = new(string)
		**out = **in
	}
	if in.PlanId != nil {
		in, out := &in.PlanId, &out.PlanId
		*out = new(string)
		**out = **in
	}
	if in.ServiceId != nil {
		in, out := &in.ServiceId, &out.ServiceId
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new InstanceData.
func (in *InstanceData) DeepCopy() *InstanceData {
	if in == nil {
		return nil
	}
	out := new(InstanceData)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KubernetesContextObject) DeepCopyInto(out *KubernetesContextObject) {
	*out = *in
	if in.Platform != nil {
		in, out := &in.Platform, &out.Platform
		*out = new(string)
		**out = **in
	}
	if in.Namespace != nil {
		in, out := &in.Namespace, &out.Namespace
		*out = new(string)
		**out = **in
	}
	if in.NamespaceAnnotations != nil {
		in, out := &in.NamespaceAnnotations, &out.NamespaceAnnotations
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.InstanceAnnotations != nil {
		in, out := &in.InstanceAnnotations, &out.InstanceAnnotations
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.ClusterId != nil {
		in, out := &in.ClusterId, &out.ClusterId
		*out = new(string)
		**out = **in
	}
	if in.InstanceName != nil {
		in, out := &in.InstanceName, &out.InstanceName
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KubernetesContextObject.
func (in *KubernetesContextObject) DeepCopy() *KubernetesContextObject {
	if in == nil {
		return nil
	}
	out := new(KubernetesContextObject)
	in.DeepCopyInto(out)
	return out
}
