//go:build !ignore_autogenerated

// SPDX-FileCopyrightText: 2025 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by controller-gen. DO NOT EDIT.

package common

import (
	apiscommon "github.com/crossplane/crossplane-runtime/v2/apis/common"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ApplicationData) DeepCopyInto(out *ApplicationData) {
	*out = *in
	if in.ProviderConfigReference != nil {
		in, out := &in.ProviderConfigReference, &out.ProviderConfigReference
		*out = new(apiscommon.ProviderConfigReference)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ApplicationData.
func (in *ApplicationData) DeepCopy() *ApplicationData {
	if in == nil {
		return nil
	}
	out := new(ApplicationData)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KubernetesOSBContext) DeepCopyInto(out *KubernetesOSBContext) {
	*out = *in
	if in.NamespaceAnnotations != nil {
		in, out := &in.NamespaceAnnotations, &out.NamespaceAnnotations
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.InstanceAnnotations != nil {
		in, out := &in.InstanceAnnotations, &out.InstanceAnnotations
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KubernetesOSBContext.
func (in *KubernetesOSBContext) DeepCopy() *KubernetesOSBContext {
	if in == nil {
		return nil
	}
	out := new(KubernetesOSBContext)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KubernetesOSBOriginatingIdentityExtra) DeepCopyInto(out *KubernetesOSBOriginatingIdentityExtra) {
	*out = *in
	if in.Raw != nil {
		in, out := &in.Raw, &out.Raw
		*out = make([]byte, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KubernetesOSBOriginatingIdentityExtra.
func (in *KubernetesOSBOriginatingIdentityExtra) DeepCopy() *KubernetesOSBOriginatingIdentityExtra {
	if in == nil {
		return nil
	}
	out := new(KubernetesOSBOriginatingIdentityExtra)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KubernetesOSBOriginatingIdentityValue) DeepCopyInto(out *KubernetesOSBOriginatingIdentityValue) {
	*out = *in
	if in.Groups != nil {
		in, out := &in.Groups, &out.Groups
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.Extra != nil {
		in, out := &in.Extra, &out.Extra
		*out = new(KubernetesOSBOriginatingIdentityExtra)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KubernetesOSBOriginatingIdentityValue.
func (in *KubernetesOSBOriginatingIdentityValue) DeepCopy() *KubernetesOSBOriginatingIdentityValue {
	if in == nil {
		return nil
	}
	out := new(KubernetesOSBOriginatingIdentityValue)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NamespacedName) DeepCopyInto(out *NamespacedName) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NamespacedName.
func (in *NamespacedName) DeepCopy() *NamespacedName {
	if in == nil {
		return nil
	}
	out := new(NamespacedName)
	in.DeepCopyInto(out)
	return out
}
