apiVersion:  binding.osb.m.crossplane.io/v1alpha1
kind: ServiceBinding
metadata:
  name: e2e-test-binding
  namespace: crossplane-system
spec:
  providerConfigRef:
    name: osb-provider
    kind: ProviderConfig
  forProvider:
    parameters: |
      {
        "backend_ip": "10.0.0.5",
        "server_name": "example.com",
        "ssl_certificate": "-----BEGIN CERTIFICATE----- ... -----END CERTIFICATE-----",
        "ssl_certificate_key": "-----BEGIN PRIVATE KEY----- ... -----END PRIVATE KEY-----"
      }
    context:
      platform: kubernetes
      clusterId: my-cluster-id
      namespace: crossplane-system
      instanceName: e2e-test-instance
    appGuid: my-app-guid
    instanceId: 123e4567-e89b-12d3-a456-426614174000
    serviceId: test-service-id
    planId: 123e4567-e89b-12d3-a456-426614174000
